services:
  nginx:
    image: nginx:1.19.6-alpine
    volumes:
      - ./backend-nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4000:4000"
    depends_on:
      - app-backend
  app-backend:
    image: node:20.18.0-alpine
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./.container/logs:/app/logs
      - ./.container/data:/app/data
      - ./.container/node_modules:/app/node_modules
    working_dir: /app
    command: npm run dev
