services:
  # nodejs backend
  backend:
    image: node:20.18.0-alpine
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./node_modules:/app/node_modules
      - ./.container/logs:/app/logs
      - ./.container/data:/app/data
    ports:
      - "4000:4000"
    working_dir: /app
    command: npm run ${NODE_ENV}

  # central cache
  redis:
    image: redis:6.2.5-alpine
    volumes:
      - ./.container/redis/data:/data
    ports:
      - "6379:6379"

  # database
  mysql:
    image: mysql:8.0.40
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=development
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./.secrets/mysql-root:/run/secrets/mysql-root
      - ./.container/mysql:/var/lib/mysql

  # reverse proxy
  nginx:
    profiles:
      - donotstart
    image: nginx:1.27.3-alpine
    volumes:
      - ./backend-nginx.conf:/etc/nginx/templates/default.conf.template
      - ./.container/nginx/logs:/var/log/nginx
    environment:
      - BACKEND_SERVER=app-backend:4000
      - SERVER_NAME=localhost
      - NGINX_PORT=80
    ports:
      - "80:80"
